@startuml diagrama_pacotes_aluguel
skinparam shadowing false
skinparam packageStyle rectangle

package "br.edu.pucminas.aluguel" {
  package controller {
    class ClienteController
    class PedidoController
    class AcessoController
  }
  package service {
    class ClienteService
    class PedidoService
  }
  package repository {
    interface ClienteRepository
    interface PedidoRepository
    interface AutomovelRepository
  }
  package model {
    class Usuario
    class Cliente
    class Empregador
    class Automovel
    class PedidoAluguel
  }
  package dto {
    class ClienteForm
    class PedidoForm
  }
  package config {
    class SegurancaConfig
    class AutomoveisIniciais
  }
}

package "templates Thymeleaf" as templates {
  class "acesso/*.html" as acesso <<view>>
  class "clientes/*.html" as clientes <<view>>
  class "pedidos/*.html" as pedidos <<view>>
}
class "H2" as banco <<database>>

controller ..> dto
controller --> service
controller --> templates : escolhe página
service --> repository
service --> model
repository --> model
repository --> banco : JPA
config ..> controller : protege rotas
config ..> repository : carrega catálogo
@enduml
